version: "3.9"

networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  user_management:
    build:
      context: .
      dockerfile: user_management/Dockerfile
    volumes:
      - ./user_management:/workspace/user_management
    ports:
      - "8001:8001"
    depends_on:
      - db_user_management
    networks:
      - transcendence

  db_user_management:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: db_user_management
    ports:
      - "5433:5432" # Map internal 5432 to external 5433
    volumes:
      - postgres_user_management:/var/lib/postgresql/data
    networks:
      - transcendence

  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    volumes:
      - ./chat:/workspace/chat
    ports:
      - "8000:8000"
    depends_on:
      - user_management
      - db_chat
    networks:
      - transcendence

  db_chat:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: db_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_chat:/var/lib/postgresql/data
    networks:
      - transcendence

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - transcendence

volumes:
  postgres_user_management:
  postgres_chat: