services:
  tournament:
    build: ./web3-tournament
    container_name: web3-tournament
    restart: always
    env_file: ./.env
    networks:
      - docker-network
    depends_on:
      - ethereum-testnet
    volumes:
      - ethereum-testnet:/data/
    #   - adminer:/data/adminer
    #   - mariadb:/data/mysql
    #   - website:/data/website
    # expose:
    #   - 8546 #
  ethereum-testnet:
    build: ./ethereum-testnet
    container_name: ethereum-testnet
    restart: always
    env_file: ./.env
    volumes:
      - ethereum-testnet:/data/
    networks:
      - docker-network
    # expose:
    #   - 85450
    # ports:
    #   - 80:80

networks:
  docker-network:
    driver: bridge

volumes:
  ethereum-testnet:

# volumes:
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/tmp/mariadb'
